import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "title": "Happy Shop",
          "explanation": "The right address for your shopping",
          "skip": "Skip",
          "user_login": "User Login",
          "admin_login": "Admin  Login",
          "continue_without_login": "Continue Without Login",
          "your_informaiton": "YOUR INFORMATION",
          "bodySize": "Body Size",
          "shoeSize": "Shoe Size",
          "okey": "OKEY",
          "userPage": "USER PAGE",
          "adminPage": "ADMIN PAGE",
          "login": "Login",
          "register": "REGİSTER",
          "kullaniciGirisi": "USER LOGIN",
          "eposta": "E posta",
          "password": "password",
          "enter": "ENTER",
          "sıgnIn": "SIGIN IN",
          "adminLogin": "ADMIN LOGIN",
          "adminPanel": "ADMIN PANEL",
          "urunName": "Product Name: ",
          "create": "CREATE",
          "update": "UPDATE",
          "delete": "DELETE",
          "product_added": "Product Added",
          "product_updated": "Product Updated",
          "product_deleted": "Product Deleted",
          "kategori": "Categori: ",
          "home": "Home",
          "admin": "Admin",
          "exit": "Exit",
          "size": "Size: ",
          "bodysec": "Clothes",
          "shoesec": "Shoes",
          "enterProductName": "Enter Product Name",
          "choose_category": "Choose Category",
          "enter_product_price": "Enter Product Price",
          "enter_the_number_of_products": "Enter The Number Of Products",
          "number_of_products": "Number Of Products",
          "product_price": "Product Price",
          "total": " Total",
          "price": "Price ",
          "categories": "Categories",
          "clothes": "Clothes",
          "shoes": "Shoes",
          "discount": "Discount",
          "mainPage": "Main Page",
          "basket": "Basket",
          "favorites": "Favorites",
          "profile": "Profile",
          "products_in_the_basket": "Products In The Basket",
          "total_amount": "Total Amount",
          "complete_the_order": "Complete The Order",
          "favorites_": "Favorites",
          "product": "Product",
          "edit_profile": "Edit Profile",
          "change_password": "Change Password",
          "previous_orders": "Previous Orders",
          "kvkk_and_terms_of_use": "KVKK and terms of use",
          "sign_out": "Sign Out",
          "hatali": "Email or password is incorrect",
          "add_to_Basket": "Add Basket",
          "sameEposta":
              "Email address is already in use by another account. Try again with another email address.",
          "hata": "WARNING"
        },
        'tr_TR': {
          "title": "MUTLU ALIŞVERİŞ",
          "explanation": "Alışveriş için doğru adrestesiniz",
          "skip": "Atla",
          "user_login": "Kullanıcı girişi",
          "admin_login": "Yönetici girişi",
          "continue_without_login": "giriş yapmadan devam et",
          "your_informaiton": "bilgilerinizi giriniz",
          "bodySize": "Beden: ",
          "shoeSize": "Ayakkabı Num: ",
          "okey": "TAMAM",
          "userPage": "KULLANICI SAYFASI",
          "adminPage": "YÖNETİCİ SAYFASI",
          "login": "Giriş",
          "kullaniciGirisi": "KULLANICI GİRİŞİ",
          "eposta": "E posta",
          "password": "Şifre",
          "enter": "GİRİŞ",
          "register": "KAYIT OL",
          "sıgnIn": "KAYIT",
          "adminLogin": "YÖNETİCİ GİRİŞİ",
          "adminPanel": "ADMIN PANEL",
          "urunName": "Ürün Adı: ",
          "create": "OLUŞTUR",
          "update": "GÜNCELLE",
          "delete": "SİL",
          "product_added": "Ürün Eklendi",
          "product_updated": "Ürün Güncellendi",
          "product_deleted": "Ürün Silindi",
          "veriler": "VERİLER",
          "kategori": "Kategori: ",
          "home": "Ana Sayfa",
          "admin": "Yönetici",
          "exit": "Çıkış",
          "size": "Numara & Beden: ",
          "bodysec": "Kıyafet",
          "shoesec": "Ayakkabı",
          "enterProductName": "Ürün Adını Girin",
          "choose_category": "Kategori Seçiniz",
          "enter_product_price": "Ürün Fiyatı Giriniz",
          "enter_the_number_of_products": "Ürün Sayısı Girin",
          "number_of_products": "Ürün Sayısı",
          "product_price": "ürün Fiyatı",
          "total": " Adet",
          "price": "Fiyat: ",
          "categories": "Kategoriler",
          "clothes": "Kıyafetler",
          "shoes": "Ayakkabılar",
          "discount": "İndirim",
          "mainPage": "Anasayfa",
          "basket": "Sepet",
          "favorites": "Favorilerim",
          "profile": "Profil",
          "products_in_the_basket": "Sepetteki Ürünler",
          "total_amount": "Toplam Tutar",
          "complete_the_order": "Siparişi Tamamla",
          "favorites_": "Favoriler",
          "add_to_Basket": "Sepete Ekle",
          "product": "Ürün",
          "edit_profile": "profili düzenle",
          "change_password": "Şifre değiştir",
          "previous_orders": "Önceki Siparişler",
          "kvkk_and_terms_of_use": "KVKK ve kullanım koşulları",
          "sign_out": "Çıkış Yap",
          "sameEposta":
              "E-posta adresi zaten başka bir hesap tarafından kullanılıyor. Başka bir e-posta adresi ile tekrar deneyin.",
          "hatali": "E-posta veya şifre yanlış",
          "hata": "HATA"
        }
      };
}
